#include "murm/ne_cache.h"

#include <fstream>
#include <sstream>
#include <stdexcept>

// The generator hash is defined by CMake (sha256 of murm/height_family.cpp). The
// fallback only fires if the build system did not set it.
#ifndef NE_GENERATOR_HASH
#define NE_GENERATOR_HASH "NE_GENERATOR_HASH-undefined"
#endif

namespace at::murm {

const char* ne_generator_hash() { return NE_GENERATOR_HASH; }

void write_ne_cache(const std::string& path, const NeCacheHeader& header,
                    const std::vector<NeRow>& rows) {
    std::ofstream os(path);
    if (!os) throw std::runtime_error("write_ne_cache: cannot open " + path);
    os << "# ne_cache v" << header.format_version
       << " — ORACLE-PROVENANCE INPUT DATA (m4-pinning §P4/C3; RESEARCH-M §2 amendment).\n"
       << "# Conductor N(E) and root number ε(E) for the height-ordered family\n"
       << "#   {E_{A,B}: y²=x³+Ax+B, H(E)=max(4|A|³,27B²) ≤ X, reduced, nonsingular}.\n"
       << "# N, eps are OBTAINED FROM AN ORACLE (PARI/GP) — a live oracle supplying\n"
       << "# trusted INPUT, not refereeing our numbers; a_p stays COMPUTED (ap_charsum).\n"
       << "# Residual risk: a systematic oracle N/ε error propagates silently — certified\n"
       << "# against pinned ecdata by verify/m4/oracle_dual_overlap_NE (5676 classes exact).\n"
       << "# Generated by: `at ne-cache --X " << header.X << " --out " << path << "`.\n"
       << "# Oracle: PARI/GP " << header.pari_version
       << ", ellglobalred(ellinit([0,0,0,A,B]))[1] (N), ellrootno (eps).\n"
       << "# provenance: oracle   (columns N, eps)\n"
       << "# format_version " << header.format_version << "\n"
       << "# generator_hash " << header.generator_hash << "\n"
       << "# X " << header.X << "\n"
       << "# count " << header.count << "\n"
       << "# A B N eps\n";
    for (const NeRow& r : rows)
        os << r.A << ' ' << r.B << ' ' << r.N << ' ' << r.eps << '\n';
    if (!os) throw std::runtime_error("write_ne_cache: write failed for " + path);
}

std::vector<NeRow> read_ne_cache(const std::string& path, NeCacheHeader& out) {
    std::ifstream is(path);
    if (!is) throw std::runtime_error("read_ne_cache: cannot open " + path);

    bool saw_fmt = false, saw_hash = false, saw_X = false, saw_count = false;
    std::vector<NeRow> rows;
    std::string line;
    while (std::getline(is, line)) {
        if (line.empty()) continue;
        if (line[0] == '#') {
            // Parse the machine-readable metadata comment lines.
            std::istringstream ms(line.substr(1));
            std::string key;
            ms >> key;
            if (key == "format_version") { ms >> out.format_version; saw_fmt = true; }
            else if (key == "generator_hash") { ms >> out.generator_hash; saw_hash = true; }
            else if (key == "X") { ms >> out.X; saw_X = true; }
            else if (key == "count") { ms >> out.count; saw_count = true; }
            // (pari_version and the prose lines are provenance only, not parsed as gates)
            continue;
        }
        NeRow r;
        std::istringstream rs(line);
        if (!(rs >> r.A >> r.B >> r.N >> r.eps))
            throw std::runtime_error("read_ne_cache: malformed row: " + line);
        if (r.eps != 1 && r.eps != -1)
            throw std::runtime_error("read_ne_cache: root number not ±1 in row: " + line);
        rows.push_back(r);
    }

    if (!(saw_fmt && saw_hash && saw_X && saw_count))
        throw std::runtime_error("read_ne_cache: missing header field(s) in " + path);
    if (out.format_version != kNeCacheFormatVersion)
        throw std::runtime_error("read_ne_cache: unsupported format version");

    // The refusal that matters: a cache whose family-enumeration generator differs
    // from HEAD's is stale and is NEVER silently reused (ap_cache pattern, §C3).
    if (out.generator_hash != ne_generator_hash())
        throw std::runtime_error(
            "read_ne_cache: REFUSED — stale N/ε cache: generator hash " +
            out.generator_hash + " != current " + ne_generator_hash() +
            " (regenerate with `at ne-cache`; never reuse a stale one)");

    if (static_cast<i64>(rows.size()) != out.count)
        throw std::runtime_error("read_ne_cache: row count " +
            std::to_string(rows.size()) + " != header count " +
            std::to_string(out.count) + " in " + path);
    return rows;
}

}  // namespace at::murm
