#include "murm/rank_cache.h"

#include <fstream>
#include <sstream>
#include <stdexcept>

// The generator hash is defined by CMake (sha256 of murm/height_family.cpp — the SAME
// (A,B) key generator as ne_cache). The fallback only fires if the build system did not
// set it.
#ifndef RANK_GENERATOR_HASH
#define RANK_GENERATOR_HASH "RANK_GENERATOR_HASH-undefined"
#endif

namespace at::murm {

const char* rank_generator_hash() { return RANK_GENERATOR_HASH; }

void write_rank_cache(const std::string& path, const RankCacheHeader& header,
                      const std::vector<RankRow>& rows) {
    std::ofstream os(path);
    if (!os) throw std::runtime_error("write_rank_cache: cannot open " + path);
    os << "# rank_cache v" << header.format_version
       << " — ORACLE-PROVENANCE analytic-rank column (PR-2 Amendment 1/2; RESEARCH-M §2).\n"
       << "# r(E) = ord_{s=1} L(E,s), the ANALYTIC rank, for the height-ordered family\n"
       << "#   {E_{A,B}: y²=x³+Ax+B, H(E)=max(4|A|³,27B²) ≤ X, reduced, nonsingular}.\n"
       << "# r is OBTAINED FROM AN ORACLE (PARI/GP ellanalyticrank) — numerically\n"
       << "# determined; NEVER the Mordell–Weil rank (that equality is BSD, never asserted).\n"
       << "# Safeguard: analytic-rank parity == cached ε parity for every curve (ε=(−1)^r is\n"
       << "# the functional-equation sign, a theorem); a mismatch aborts `at rank-cache`.\n"
       << "# Generated by: `at rank-cache --X " << header.X << " --out " << path << "`.\n"
       << "# Oracle: PARI/GP " << header.pari_version
       << ", ellanalyticrank(ellinit([0,0,0,A,B])) (prec " << header.prec << ").\n"
       << "# provenance: oracle-analytic-rank   (column rank)\n"
       << "# format_version " << header.format_version << "\n"
       << "# generator_hash " << header.generator_hash << "\n"
       << "# X " << header.X << "\n"
       << "# count " << header.count << "\n"
       << "# A B rank\n";
    for (const RankRow& r : rows)
        os << r.A << ' ' << r.B << ' ' << r.rank << '\n';
    if (!os) throw std::runtime_error("write_rank_cache: write failed for " + path);
}

std::vector<RankRow> read_rank_cache(const std::string& path, RankCacheHeader& out) {
    std::ifstream is(path);
    if (!is) throw std::runtime_error("read_rank_cache: cannot open " + path);

    bool saw_fmt = false, saw_hash = false, saw_X = false, saw_count = false;
    std::vector<RankRow> rows;
    std::string line;
    while (std::getline(is, line)) {
        if (line.empty()) continue;
        if (line[0] == '#') {
            std::istringstream ms(line.substr(1));
            std::string key;
            ms >> key;
            if (key == "format_version") { ms >> out.format_version; saw_fmt = true; }
            else if (key == "generator_hash") { ms >> out.generator_hash; saw_hash = true; }
            else if (key == "X") { ms >> out.X; saw_X = true; }
            else if (key == "count") { ms >> out.count; saw_count = true; }
            // (pari_version, prec, prose lines are provenance only, not parsed as gates)
            continue;
        }
        RankRow r;
        std::istringstream rs(line);
        if (!(rs >> r.A >> r.B >> r.rank))
            throw std::runtime_error("read_rank_cache: malformed row: " + line);
        if (r.rank < 0)
            throw std::runtime_error("read_rank_cache: negative rank in row: " + line);
        rows.push_back(r);
    }

    if (!(saw_fmt && saw_hash && saw_X && saw_count))
        throw std::runtime_error("read_rank_cache: missing header field(s) in " + path);
    if (out.format_version != kRankCacheFormatVersion)
        throw std::runtime_error("read_rank_cache: unsupported format version");

    // The refusal that matters: a cache whose family-enumeration generator differs from
    // HEAD's is stale and is NEVER silently reused (same guard as ne_cache).
    if (out.generator_hash != rank_generator_hash())
        throw std::runtime_error(
            "read_rank_cache: REFUSED — stale rank cache: generator hash " +
            out.generator_hash + " != current " + rank_generator_hash() +
            " (regenerate with `at rank-cache`; never reuse a stale one)");

    if (static_cast<i64>(rows.size()) != out.count)
        throw std::runtime_error("read_rank_cache: row count " +
            std::to_string(rows.size()) + " != header count " +
            std::to_string(out.count) + " in " + path);
    return rows;
}

}  // namespace at::murm
