#include <fstream>
#include <sstream>
#include <stdexcept>
#include <vector>

#include "murm/ss_density.h"     // extract_shape
#include "murm/ss_empirical.h"

// Committed empirical-run I/O + the generator-hash accessor + the windowed-trough
// diagnostic. Deliberately SEPARATE from ss_empirical.cpp: the run's generator hash
// (SS_GENERATOR_HASH, wired in CMake) is the sha256 of ss_empirical.cpp — the source
// of the NUMBERS in the committed file — so editing this reader/format/diagnostic does
// NOT invalidate a committed run (only a change to the statistic itself does).
#ifndef SS_GENERATOR_HASH
#define SS_GENERATOR_HASH "SS_GENERATOR_HASH-undefined"
#endif

namespace at::murm {

const char* ss_generator_hash() { return SS_GENERATOR_HASH; }

double windowed_trough_u(const SSEmpirical& e, double u_lo, double u_hi) {
    std::vector<double> us, ds;
    for (std::size_t b = 0; b < e.u_mid.size(); ++b)
        if (e.u_mid[b] >= u_lo && e.u_mid[b] <= u_hi) {
            us.push_back(e.u_mid[b]);
            ds.push_back(e.density[b]);
        }
    if (us.empty()) return -1;
    return extract_shape(us, ds).trough_u;
}

void write_ss_run(const std::string& path, const SSRun& run) {
    std::ofstream os(path);
    if (!os) throw std::runtime_error("write_ss_run: cannot open " + path);
    os << "# ss_empirical v" << run.format_version
       << " — COMPUTED empirical statistic (1) of [SS25] (height murmuration).\n"
       << "# a_p COMPUTED from scratch (ell::ap_fast, twinned vs the frozen ell::ap_charsum);\n"
       << "# N, ε are oracle-provenance INPUT (data/m4/ne_cache.txt, R3-certified). The claim\n"
       << "# is empirical agreement with the CONJECTURED density (Conjecture 1 [SS25]), not a\n"
       << "# proof. Generated by `at ss-run`; regenerate if the statistic source changes.\n"
       << "# format_version " << run.format_version << "\n"
       << "# generator_hash " << run.generator_hash << "\n"
       << "# X_confirm " << run.X_confirm << "\n"
       << "# du " << run.du << "\n"
       << "# tol " << run.tol << "\n"
       << "# r2 " << run.r2_hump << ' ' << run.r2_zero << ' ' << run.r2_trough << "\n";
    os << "# ladder";
    for (double x : run.ladder) os << ' ' << x;
    os << "\n# shape X n_curves hump_u hump_v zero_u trough_u trough_v\n";
    for (const SSScaleShape& s : run.shapes)
        os << "shape " << s.X << ' ' << s.n_curves << ' ' << s.shape.hump_u << ' '
           << s.shape.hump_v << ' ' << s.shape.zero_u << ' ' << s.shape.trough_u << ' '
           << s.shape.trough_v << "\n";
    os << "# curve u_mid density count   (at X_confirm=" << run.X_confirm << ")\n";
    for (std::size_t b = 0; b < run.confirm.u_mid.size(); ++b)
        os << "curve " << run.confirm.u_mid[b] << ' ' << run.confirm.density[b] << ' '
           << run.confirm.count[b] << "\n";
    if (!os) throw std::runtime_error("write_ss_run: write failed for " + path);
}

SSRun read_ss_run(const std::string& path) {
    std::ifstream is(path);
    if (!is) throw std::runtime_error("read_ss_run: cannot open " + path);
    SSRun r;
    bool saw_fmt = false, saw_hash = false;
    std::string line;
    while (std::getline(is, line)) {
        if (line.empty()) continue;
        if (line[0] == '#') {
            std::istringstream ms(line.substr(1));
            std::string key; ms >> key;
            if (key == "format_version") { ms >> r.format_version; saw_fmt = true; }
            else if (key == "generator_hash") { ms >> r.generator_hash; saw_hash = true; }
            else if (key == "X_confirm") ms >> r.X_confirm;
            else if (key == "du") ms >> r.du;
            else if (key == "tol") ms >> r.tol;
            else if (key == "r2") ms >> r.r2_hump >> r.r2_zero >> r.r2_trough;
            else if (key == "ladder") { double x; while (ms >> x) r.ladder.push_back(x); }
            continue;
        }
        std::istringstream rs(line);
        std::string tag; rs >> tag;
        if (tag == "shape") {
            SSScaleShape s;
            rs >> s.X >> s.n_curves >> s.shape.hump_u >> s.shape.hump_v >> s.shape.zero_u
               >> s.shape.trough_u >> s.shape.trough_v;
            r.shapes.push_back(s);
        } else if (tag == "curve") {
            double u, d; i64 n;
            rs >> u >> d >> n;
            r.confirm.u_mid.push_back(u);
            r.confirm.density.push_back(d);
            r.confirm.count.push_back(n);
        }
    }
    if (!(saw_fmt && saw_hash))
        throw std::runtime_error("read_ss_run: missing header field(s) in " + path);
    if (r.format_version != kSSRunFormatVersion)
        throw std::runtime_error("read_ss_run: unsupported format version");
    if (r.generator_hash != ss_generator_hash())
        throw std::runtime_error(
            "read_ss_run: REFUSED — stale empirical run: generator hash " +
            r.generator_hash + " != current " + ss_generator_hash() +
            " (regenerate with `at ss-run`; never reuse a stale one)");
    r.confirm.X = r.X_confirm;
    r.confirm.du = r.du;
    for (const SSScaleShape& s : r.shapes)
        if (s.X == r.X_confirm) { r.confirm.n_curves = s.n_curves; r.confirm.shape = s.shape; }
    return r;
}

}  // namespace at::murm
