#include <fstream>
#include <iomanip>
#include <limits>
#include <sstream>
#include <stdexcept>
#include <vector>

#include "murm/ss_density.h"     // extract_shape
#include "murm/ss_empirical.h"

// Committed empirical-run I/O + the generator-hash accessor + the windowed-trough
// diagnostic. Deliberately SEPARATE from ss_empirical.cpp: the run's generator hash
// (SS_GENERATOR_HASH, wired in CMake) is the sha256 of ss_empirical.cpp — the source
// of the NUMBERS in the committed file — so editing this reader/format/diagnostic does
// NOT invalidate a committed run (only a change to the statistic itself does).
#ifndef SS_GENERATOR_HASH
#define SS_GENERATOR_HASH "SS_GENERATOR_HASH-undefined"
#endif

namespace at::murm {

const char* ss_generator_hash() { return SS_GENERATOR_HASH; }

double windowed_trough_u(const SSEmpirical& e, double u_lo, double u_hi) {
    std::vector<double> us, ds;
    for (std::size_t b = 0; b < e.u_mid.size(); ++b)
        if (e.u_mid[b] >= u_lo && e.u_mid[b] <= u_hi) {
            us.push_back(e.u_mid[b]);
            ds.push_back(e.density[b]);
        }
    if (us.empty()) return -1;
    return extract_shape(us, ds).trough_u;
}

void write_ss_run(const std::string& path, const SSRun& run) {
    std::ofstream os(path);
    if (!os) throw std::runtime_error("write_ss_run: cannot open " + path);
    os << "# ss_empirical v" << run.format_version
       << " — COMPUTED empirical statistic (1) of [SS25] (height murmuration).\n"
       << "# a_p COMPUTED from scratch (ell::ap_fast, twinned vs the frozen ell::ap_charsum);\n"
       << "# N, ε are oracle-provenance INPUT (the committed ne_cache, R3-certified). The claim\n"
       << "# is empirical agreement with the CONJECTURED density (Conjecture 1 [SS25]), not a\n"
       << "# proof. Generated by `at ss-run`; regenerate if the statistic source changes.\n"
       << "# format_version " << run.format_version << "\n"
       << "# generator_hash " << run.generator_hash << "\n"
       << "# X_confirm " << run.X_confirm << "\n"
       << "# du " << run.du << "\n"
       << "# tol " << run.tol << "\n"
       << "# r2 " << run.r2_hump << ' ' << run.r2_zero << ' ' << run.r2_trough << "\n";
    os << "# ladder";
    for (double x : run.ladder) os << ' ' << x;
    os << "\n# shape X n_curves hump_u hump_v zero_u trough_u trough_v\n";
    for (const SSScaleShape& s : run.shapes)
        os << "shape " << s.X << ' ' << s.n_curves << ' ' << s.shape.hump_u << ' '
           << s.shape.hump_v << ' ' << s.shape.zero_u << ' ' << s.shape.trough_u << ' '
           << s.shape.trough_v << "\n";
    os << "# curve u_mid density count   (at X_confirm=" << run.X_confirm << ")\n";
    for (std::size_t b = 0; b < run.confirm.u_mid.size(); ++b)
        os << "curve " << run.confirm.u_mid[b] << ' ' << run.confirm.density[b] << ' '
           << run.confirm.count[b] << "\n";
    if (!os) throw std::runtime_error("write_ss_run: write failed for " + path);
}

SSRun read_ss_run(const std::string& path) {
    std::ifstream is(path);
    if (!is) throw std::runtime_error("read_ss_run: cannot open " + path);
    SSRun r;
    bool saw_fmt = false, saw_hash = false;
    std::string line;
    while (std::getline(is, line)) {
        if (line.empty()) continue;
        if (line[0] == '#') {
            std::istringstream ms(line.substr(1));
            std::string key; ms >> key;
            if (key == "format_version") { ms >> r.format_version; saw_fmt = true; }
            else if (key == "generator_hash") { ms >> r.generator_hash; saw_hash = true; }
            else if (key == "X_confirm") ms >> r.X_confirm;
            else if (key == "du") ms >> r.du;
            else if (key == "tol") ms >> r.tol;
            else if (key == "r2") ms >> r.r2_hump >> r.r2_zero >> r.r2_trough;
            else if (key == "ladder") { double x; while (ms >> x) r.ladder.push_back(x); }
            continue;
        }
        std::istringstream rs(line);
        std::string tag; rs >> tag;
        if (tag == "shape") {
            SSScaleShape s;
            rs >> s.X >> s.n_curves >> s.shape.hump_u >> s.shape.hump_v >> s.shape.zero_u
               >> s.shape.trough_u >> s.shape.trough_v;
            r.shapes.push_back(s);
        } else if (tag == "curve") {
            double u, d; i64 n;
            rs >> u >> d >> n;
            r.confirm.u_mid.push_back(u);
            r.confirm.density.push_back(d);
            r.confirm.count.push_back(n);
        }
    }
    if (!(saw_fmt && saw_hash))
        throw std::runtime_error("read_ss_run: missing header field(s) in " + path);
    if (r.format_version != kSSRunFormatVersion)
        throw std::runtime_error("read_ss_run: unsupported format version");
    if (r.generator_hash != ss_generator_hash())
        throw std::runtime_error(
            "read_ss_run: REFUSED — stale empirical run: generator hash " +
            r.generator_hash + " != current " + ss_generator_hash() +
            " (regenerate with `at ss-run`; never reuse a stale one)");
    r.confirm.X = r.X_confirm;
    r.confirm.du = r.du;
    for (const SSScaleShape& s : r.shapes)
        if (s.X == r.X_confirm) { r.confirm.n_curves = s.n_curves; r.confirm.shape = s.shape; }
    return r;
}

// -------- per-curve bin partials I/O (PR-1 R2) — same non-hash-bound TU -----------
void write_ss_partials(const std::string& path, const SSPartials& P,
                       const SSPartialsMeta& meta) {
    std::ofstream os(path);
    if (!os) throw std::runtime_error("write_ss_partials: cannot open " + path);
    // max_digits10 (=17) round-trips every IEEE double exactly → the reader reconstructs
    // the partials bit-for-bit, so a re-aggregation matches the in-memory shape.
    os << std::setprecision(std::numeric_limits<double>::max_digits10);
    os << "# ss_partials v" << meta.format_version
       << " — per-curve bin partials of COMPUTED statistic (1) of [SS25] (height murmuration).\n"
       << "# num[c][b] = Σ_{(E,p): p/N∈bin_b} (u_mid·lnN/N)·ε·a_p   (ε folded in).\n"
       << "# a_p COMPUTED from scratch (ell::ap_fast, twinned vs frozen ell::ap_charsum);\n"
       << "# N, ε are oracle-provenance INPUT (ne_cache below, R3-certified oracle_dual_overlap_NE).\n"
       << "# Persisted so PR-2 re-aggregates subpopulations with NO a_p recompute (add the\n"
       << "# analytic-rank column, re-sum). Regenerate if the statistic source changes.\n"
       << "# provenance computed(a_p)+oracle(N,eps)\n"
       << "# format_version " << meta.format_version << "\n"
       << "# generator_hash " << meta.generator_hash << "\n"
       << "# X " << meta.X << "\n"
       << "# du " << meta.du << "\n"
       << "# NB " << meta.NB << "\n"
       << "# n_curves " << meta.n_curves << "\n"
       << "# threads " << meta.threads << "\n"
       << "# complete " << (meta.complete ? 1 : 0) << "\n"
       << "# ne_cache " << meta.ne_cache << "\n"
       << "# part A B N  num[0..NB-1]  cnt[0..NB-1]\n";
    for (std::size_t c = 0; c < P.A.size(); ++c) {
        os << "part " << P.A[c] << ' ' << P.B[c] << ' ' << P.N[c];
        for (int b = 0; b < P.NB; ++b) os << ' ' << P.num[c][b];
        for (int b = 0; b < P.NB; ++b) os << ' ' << P.cnt[c][b];
        os << '\n';
    }
    if (!os) throw std::runtime_error("write_ss_partials: write failed for " + path);
}

SSPartials read_ss_partials(const std::string& path, SSPartialsMeta& out_meta,
                            bool allow_incomplete) {
    std::ifstream is(path);
    if (!is) throw std::runtime_error("read_ss_partials: cannot open " + path);
    SSPartialsMeta m;
    bool saw_fmt = false, saw_hash = false, saw_nb = false, saw_complete = false;
    int complete_flag = 0;
    SSPartials P;
    std::string line;
    while (std::getline(is, line)) {
        if (line.empty()) continue;
        if (line[0] == '#') {
            std::istringstream ms(line.substr(1));
            std::string key; ms >> key;
            if (key == "format_version") { ms >> m.format_version; saw_fmt = true; }
            else if (key == "generator_hash") { ms >> m.generator_hash; saw_hash = true; }
            else if (key == "X") ms >> m.X;
            else if (key == "du") { ms >> m.du; P.du = m.du; }
            else if (key == "NB") { ms >> m.NB; P.NB = m.NB; saw_nb = true; }
            else if (key == "n_curves") ms >> m.n_curves;
            else if (key == "threads") ms >> m.threads;
            else if (key == "complete") { ms >> complete_flag; m.complete = (complete_flag != 0); saw_complete = true; }
            else if (key == "ne_cache") ms >> m.ne_cache;
            continue;
        }
        std::istringstream rs(line);
        std::string tag; rs >> tag;
        if (tag != "part") continue;
        if (!saw_nb) throw std::runtime_error("read_ss_partials: `part` row before NB header in " + path);
        i64 A, B, N;
        rs >> A >> B >> N;
        std::vector<double> num(m.NB, 0.0);
        std::vector<i64> cnt(m.NB, 0);
        bool ok = true;
        for (int b = 0; b < m.NB && ok; ++b) if (!(rs >> num[b])) ok = false;
        for (int b = 0; b < m.NB && ok; ++b) if (!(rs >> cnt[b])) ok = false;
        if (!ok) {
            // A truncated final line = crash mid-write of the checkpoint. Only tolerable
            // when resuming (allow_incomplete); a "complete" file must never be truncated.
            if (allow_incomplete) break;
            throw std::runtime_error("read_ss_partials: truncated `part` row in " + path);
        }
        P.A.push_back(A); P.B.push_back(B); P.N.push_back(N);
        P.num.push_back(std::move(num)); P.cnt.push_back(std::move(cnt));
    }
    if (!(saw_fmt && saw_hash && saw_nb && saw_complete))
        throw std::runtime_error("read_ss_partials: missing header field(s) in " + path);
    if (m.format_version != kSSPartialsFormatVersion)
        throw std::runtime_error("read_ss_partials: unsupported format version");
    if (m.generator_hash != ss_generator_hash())
        throw std::runtime_error(
            "read_ss_partials: REFUSED — stale partials: generator hash " + m.generator_hash +
            " != current " + ss_generator_hash() + " (regenerate with `at ss-run`)");
    if (!m.complete && !allow_incomplete)
        throw std::runtime_error(
            "read_ss_partials: REFUSED — incomplete (checkpoint) partials never fed to "
            "analysis (R3 no-peeking); pass allow_incomplete only to RESUME the run");
    if (m.complete && static_cast<i64>(P.A.size()) != m.n_curves)
        throw std::runtime_error("read_ss_partials: row count != header n_curves in " + path);
    out_meta = m;
    return P;
}

}  // namespace at::murm
