#pragma once
#include <cstdint>
#include <string>
#include <vector>

// Stage M0 — the a_p cache (ARCHITECTURE-M §4). A derived artifact WITH PROVENANCE:
// invalidated by a generator-hash mismatch. The loader REFUSES a stale cache (no
// silent reuse) — the freshness principle (ERRATA #18) applied to derived data.
// Never committed (gitignored, regenerated by script); values packed as int16
// (|a_p| ≤ 2√p fits). read_ap_cache THROWS on a generator-hash mismatch: that
// refusal is DEMONSTRATED firing by the M0 tests (both directions).
namespace at::ell {

constexpr uint32_t kApCacheFormatVersion = 1;

struct ApCacheHeader {
    uint32_t format_version = kApCacheFormatVersion;
    std::string generator_hash;   // sha256 of ell/ap_fast.cpp at build (the generator)
    std::string ecdata_sha;       // ecdata pin the values were computed against
    uint64_t prime_bound = 0;
    std::string curve_set;        // descriptor of the curve set / layout
};

// The compiled-in generator hash (CMake sha256 of ell/ap_fast.cpp). A cache is
// valid only if header.generator_hash equals this.
const char* ap_generator_hash();

void write_ap_cache(const std::string& path, const ApCacheHeader& header,
                    const std::vector<int16_t>& values);

// Reads the cache into `out_header` and returns the packed values. THROWS
// std::runtime_error if the magic/format is wrong, or — the refusal that matters —
// if header.generator_hash != ap_generator_hash() (a stale cache is never reused).
std::vector<int16_t> read_ap_cache(const std::string& path, ApCacheHeader& out_header);

}  // namespace at::ell
