#!/usr/bin/env python3
"""Generate src/core/constants.h — the single source of numerical constants.

CONSTANTS DISCIPLINE (CLAUDE.md): no numerical constant is ever typed from memory.
- True mathematical values are transcribed ONCE here, from a cited source, at ≥50
  significant digits; the C++ compiler rounds them to double.
- Derived pairs (argument-reduction hi/lo splits) are COMPUTED at high precision
  (Python's stdlib `decimal`, no third-party dep) — never typed — so a hand-typed
  split can never silently corrupt large-argument reductions beneath eyeball
  precision (the CONSTANTS INCIDENT, ERRATA #24-class).

The emitted header is checked in; `ctest -R constants.regen_matches` regenerates it
and diffs the committed copy (the freshness pattern, applied to constants). Runs with
the Python standard library only (decimal), so it works everywhere including CI.

Usage: python3 oracle/gen_constants.py            # rewrite src/core/constants.h
       python3 oracle/gen_constants.py --check     # print to stdout, exit 0 (diff externally)
"""
import sys
from decimal import Decimal, getcontext

getcontext().prec = 80

# --- cited true values (≥50 significant digits) --------------------------------
# π: OEIS A000796 / standard.  Everything else is derived from π at high precision.
PI = Decimal("3.14159265358979323846264338327950288419716939937510582097494459")


def sig50(x: Decimal) -> str:
    """The value to 50 significant digits, as a plain C++ double literal (compiler rounds)."""
    from decimal import Context
    return str(+Context(prec=50).create_decimal(x))


def f_repr(x: float) -> str:
    """Shortest round-trip decimal of a double, as a C++ literal."""
    r = repr(x)
    return r if ("." in r or "e" in r or "E" in r) else r + ".0"


# --- derived quantities --------------------------------------------------------
TWO_PI = 2 * PI
HALF_PI = PI / 2
TWO_OVER_PI = 2 / PI

# π/2 argument-reduction split (Cody–Waite): hi = nearest double to π/2,
# lo = nearest double to (π/2 − hi).  COMPUTED, never typed.
half_pi_hi = float(HALF_PI)
half_pi_lo = float(HALF_PI - Decimal(half_pi_hi))
# Identity assertions at high precision (arbitrary precision via decimal):
recon_err = abs((Decimal(half_pi_hi) + Decimal(half_pi_lo)) - HALF_PI)
assert recon_err < Decimal("1e-30"), f"hi+lo does not reconstruct π/2: err={recon_err}"
assert float(HALF_PI) == half_pi_hi, "hi is not the nearest double to π/2"

HEADER = f"""// AUTO-GENERATED by oracle/gen_constants.py — DO NOT EDIT BY HAND.
// Regenerate: `python3 oracle/gen_constants.py`; guarded by ctest `constants.regen_matches`.
//
// CONSTANTS DISCIPLINE (CLAUDE.md): no numerical constant is typed from memory. True
// values are transcribed from a cited source at ≥50 digits (the compiler rounds);
// derived hi/lo splits are computed at high precision by the generator. This closes
// the numerical-transcription failure mode (the CONSTANTS INCIDENT): a hand-typed
// split is invisible to twins, because twins SHARE the constants.
#pragma once
namespace at::core {{

// π — OEIS A000796 (transcribed once, in oracle/gen_constants.py).
inline constexpr double kPi = {sig50(PI)};
// 2π
inline constexpr double kTwoPi = {sig50(TWO_PI)};
// π/2
inline constexpr double kHalfPi = {sig50(HALF_PI)};
// 2/π
inline constexpr double kTwoOverPi = {sig50(TWO_OVER_PI)};

// π/2 Cody–Waite argument-reduction split (GENERATED, never typed):
//   kHalfPiHi = nearest double to π/2;  kHalfPiLo = nearest double to (π/2 − kHalfPiHi).
// Reconstructs π/2 to ~1e-33; used by large-argument sin/cos reduction (core/bessel.cpp).
inline constexpr double kHalfPiHi = {f_repr(half_pi_hi)};
inline constexpr double kHalfPiLo = {f_repr(half_pi_lo)};

}}  // namespace at::core
"""


def main() -> int:
    import os
    out = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "src", "core", "constants.h"))
    if "--check" in sys.argv:            # print regenerated header to stdout
        sys.stdout.write(HEADER)
        return 0
    if "--verify" in sys.argv:           # freshness: committed header must match regen
        try:
            committed = open(out).read()
        except OSError as e:
            sys.stderr.write(f"gen_constants --verify: cannot read {out}: {e}\n")
            return 1
        if committed == HEADER:
            sys.stderr.write("gen_constants --verify: src/core/constants.h matches the generator (identities OK)\n")
            return 0
        sys.stderr.write("gen_constants --verify: DRIFT — src/core/constants.h != generator output. "
                         "Regenerate with `python3 oracle/gen_constants.py` and commit.\n")
        return 1
    with open(out, "w") as f:
        f.write(HEADER)
    sys.stderr.write(f"gen_constants: wrote {out}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
