// AUTO-GENERATED by oracle/gen_constants.py — DO NOT EDIT BY HAND.
// Regenerate: `python3 oracle/gen_constants.py`; guarded by ctest `constants.regen_matches`.
//
// CONSTANTS DISCIPLINE (CLAUDE.md): no numerical constant is typed from memory. True
// values are transcribed from a cited source at ≥50 digits (the compiler rounds);
// derived hi/lo splits are computed at high precision by the generator. This closes
// the numerical-transcription failure mode (the CONSTANTS INCIDENT): a hand-typed
// split is invisible to twins, because twins SHARE the constants.
#pragma once
namespace at::core {

// π — OEIS A000796 (transcribed once, in oracle/gen_constants.py).
inline constexpr double kPi = 3.1415926535897932384626433832795028841971693993751;
// 2π
inline constexpr double kTwoPi = 6.2831853071795864769252867665590057683943387987502;
// π/2
inline constexpr double kHalfPi = 1.5707963267948966192313216916397514420985846996876;
// 2/π
inline constexpr double kTwoOverPi = 0.63661977236758134307553505349005744813783858296183;

// π/2 Cody–Waite argument-reduction split (GENERATED, never typed):
//   kHalfPiHi = nearest double to π/2;  kHalfPiLo = nearest double to (π/2 − kHalfPiHi).
// Reconstructs π/2 to ~1e-33; used by large-argument sin/cos reduction (core/bessel.cpp).
inline constexpr double kHalfPiHi = 1.5707963267948966;
inline constexpr double kHalfPiLo = 6.123233995736766e-17;

}  // namespace at::core
